CREATE TABLE `details_clean` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `updated` datetime DEFAULT NULL,
  `Fate` varchar(50) DEFAULT NULL,
  `Fate_date` mediumtext,
  `ImageExists` bit(1) DEFAULT NULL,
  `ImageName` varchar(75) DEFAULT NULL,
  `Image_Owner` int(11) DEFAULT NULL,
  `Image_Creator` varchar(100) DEFAULT NULL,
  `Name` varchar(50) DEFAULT NULL,
  `Registry1` varchar(40) DEFAULT NULL,
  `Registry2` varchar(40) DEFAULT NULL,
  `Registry3` varchar(40) DEFAULT NULL,
  `Registry4` varchar(40) DEFAULT NULL,
  `Registry5` varchar(255) DEFAULT NULL,
  `VRN` varchar(255) DEFAULT NULL,
  `IMO_Number` varchar(255) DEFAULT NULL,
  `MMSI_Number` varchar(255) DEFAULT NULL,
  `Name1` varchar(50) DEFAULT NULL,
  `Name2` varchar(50) DEFAULT NULL,
  `Name2_yr` varchar(10) DEFAULT NULL,
  `Name3` varchar(50) DEFAULT NULL,
  `Name3_yr` varchar(10) DEFAULT NULL,
  `Name4` varchar(50) DEFAULT NULL,
  `Name4_yr` varchar(10) DEFAULT NULL,
  `Name5` varchar(50) DEFAULT NULL,
  `Name5_yr` varchar(10) DEFAULT NULL,
  `Name6` varchar(50) DEFAULT NULL,
  `Name6_yr` varchar(10) DEFAULT NULL,
  `Name7` varchar(50) DEFAULT NULL,
  `Name7_yr` varchar(10) DEFAULT NULL,
  `Name8` varchar(50) DEFAULT NULL,
  `Name8_yr` varchar(10) DEFAULT NULL,
  `Name9` varchar(255) DEFAULT NULL,
  `Name9_yr` varchar(255) DEFAULT NULL,
  `Name10` varchar(255) DEFAULT NULL,
  `Name10_yr` varchar(255) DEFAULT NULL,
  `Name11` varchar(255) DEFAULT NULL,
  `Name11_yr` varchar(255) DEFAULT NULL,
  `Name12` varchar(255) DEFAULT NULL,
  `Name12_yr` varchar(255) DEFAULT NULL,
  `Vessel_type1` varchar(80) DEFAULT NULL,
  `Vessel_type2` varchar(80) DEFAULT NULL,
  `Vessel_type3` varchar(255) DEFAULT NULL,
  `MeasurementsImp` varchar(50) DEFAULT NULL,
  `MeasurementsMetr` varchar(50) DEFAULT NULL,
  `Material` varchar(40) DEFAULT NULL,
  `Gt` float DEFAULT NULL,
  `Rt` float DEFAULT NULL,
  `Nt` float DEFAULT NULL,
  `Dp` float DEFAULT NULL,
  `Eng_Power` varchar(200) DEFAULT NULL,
  `EngMfr` varchar(70) DEFAULT NULL,
  `Propulsion` varchar(50) DEFAULT NULL,
  `Repower` mediumtext,
  `Blt_yr` varchar(20) DEFAULT NULL,
  `BltPlace` varchar(50) DEFAULT NULL,
  `Blt_Prov` varchar(50) DEFAULT NULL,
  `BltCountry` varchar(50) DEFAULT NULL,
  `VessBldr` varchar(100) DEFAULT NULL,
  `Yard_no` varchar(30) DEFAULT NULL,
  `Designer` varchar(70) DEFAULT NULL,
  `Re_builds` mediumtext,
  `Pendant` varchar(50) DEFAULT NULL,
  `Call_sign` varchar(40) DEFAULT NULL,
  `Masters` mediumtext,
  `Owners` mediumtext,
  `Armament` mediumtext,
  `Name_significance` mediumtext,
  `Named_features` mediumtext,
  `Anecdotes` mediumtext,
  `References` mediumtext,
  `Record_Creator` varchar(255) DEFAULT NULL,
  `Record_Updater` varchar(255) DEFAULT NULL,
  `Wreck_flag` bit(1) DEFAULT NULL,
  `HerReg_flag` bit(1) DEFAULT NULL,
  `WCHVR_flag` bit(1) DEFAULT NULL,
  `WCHVR_date` datetime DEFAULT NULL,
  `WCHVR_SOS` mediumtext,
  `rcn` bit(1) DEFAULT NULL,
  `xcn` bit(1) DEFAULT NULL,
  `govt` bit(1) DEFAULT NULL,
  `rcaf` bit(1) DEFAULT NULL,
  `army` bit(1) DEFAULT NULL,
  `rn` bit(1) DEFAULT NULL,
  `nwp` bit(1) DEFAULT NULL,
  `rcmp` bit(1) DEFAULT NULL,
  `mb` bit(1) DEFAULT NULL,
  `fr` bit(1) DEFAULT NULL,
  `circum` bit(1) DEFAULT NULL,
  `whaling` bit(1) DEFAULT NULL,
  `FSV` bit(1) DEFAULT NULL,
  `Her1976` bit(1) DEFAULT NULL,
  `Her1977` bit(1) DEFAULT NULL,
  `Her1978` bit(1) DEFAULT NULL,
  `Her1979` bit(1) DEFAULT NULL,
  `Her1980` bit(1) DEFAULT NULL,
  `Her1981` bit(1) DEFAULT NULL,
  `Her1982` bit(1) DEFAULT NULL,
  `Her1983` bit(1) DEFAULT NULL,
  `Her1984` bit(1) DEFAULT NULL,
  `Her1985` bit(1) DEFAULT NULL,
  `Her1986` bit(1) DEFAULT NULL,
  `Her1987` bit(1) DEFAULT NULL,
  `Her1988` bit(1) DEFAULT NULL,
  `Her1989` bit(1) DEFAULT NULL,
  `Her1990` bit(1) DEFAULT NULL,
  `Interior` bit(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;